/* ========================================
   Surf & Ski - Ski Resorts Data
   Last updated: February 2026
   Sources: J2Ski, OnTheSnow, WeatherToSki
   ======================================== */

const skiResorts = [
    // ========== FRANCE ==========
    {
        id: "chamonix",
        name: "Chamonix Mont-Blanc",
        region: "Haute-Savoie",
        country: "France",
        altitude: { min: 1035, max: 3842 },
        snowBase: { lower: 105, upper: 260 },
        recentSnow: 25,
        price: 57,
        slopes: 155,
        lifts: 47,
        popular: true,
        website: "https://www.chamonix.com"
    },
    {
        id: "val-thorens",
        name: "Val Thorens",
        region: "Savoie",
        country: "France",
        altitude: { min: 2300, max: 3230 },
        snowBase: { lower: 150, upper: 220 },
        recentSnow: 35,
        price: 70,
        slopes: 150,
        lifts: 29,
        popular: true,
        website: "https://www.valthorens.com"
    },
    {
        id: "les-2-alpes",
        name: "Les 2 Alpes",
        region: "Isère",
        country: "France",
        altitude: { min: 1300, max: 3600 },
        snowBase: { lower: 80, upper: 200 },
        recentSnow: 50,
        price: 56,
        slopes: 200,
        lifts: 47,
        popular: true,
        website: "https://www.les2alpes.com"
    },
    {
        id: "tignes",
        name: "Tignes",
        region: "Savoie",
        country: "France",
        altitude: { min: 1550, max: 3456 },
        snowBase: { lower: 99, upper: 170 },
        recentSnow: 30,
        price: 62,
        slopes: 150,
        lifts: 39,
        popular: true,
        website: "https://www.tignes.net"
    },
    {
        id: "val-disere",
        name: "Val d'Isère",
        region: "Savoie",
        country: "France",
        altitude: { min: 1850, max: 3456 },
        snowBase: { lower: 95, upper: 175 },
        recentSnow: 28,
        price: 65,
        slopes: 150,
        lifts: 41,
        popular: true,
        website: "https://www.valdisere.com"
    },
    {
        id: "alpe-dhuez",
        name: "Alpe d'Huez",
        region: "Isère",
        country: "France",
        altitude: { min: 1250, max: 3330 },
        snowBase: { lower: 120, upper: 250 },
        recentSnow: 45,
        price: 58,
        slopes: 250,
        lifts: 81,
        popular: true,
        website: "https://www.alpedhuez.com"
    },
    {
        id: "la-plagne",
        name: "La Plagne",
        region: "Savoie",
        country: "France",
        altitude: { min: 1250, max: 3250 },
        snowBase: { lower: 85, upper: 190 },
        recentSnow: 25,
        price: 59,
        slopes: 225,
        lifts: 74,
        popular: true,
        website: "https://www.la-plagne.com"
    },
    {
        id: "les-arcs",
        name: "Les Arcs",
        region: "Savoie",
        country: "France",
        altitude: { min: 1200, max: 3226 },
        snowBase: { lower: 70, upper: 190 },
        recentSnow: 22,
        price: 58,
        slopes: 200,
        lifts: 54,
        popular: true,
        website: "https://www.lesarcs.com"
    },
    {
        id: "meribel",
        name: "Méribel",
        region: "Savoie",
        country: "France",
        altitude: { min: 1450, max: 2950 },
        snowBase: { lower: 82, upper: 188 },
        recentSnow: 30,
        price: 68,
        slopes: 150,
        lifts: 41,
        popular: true,
        website: "https://www.meribel.net"
    },
    {
        id: "courchevel",
        name: "Courchevel",
        region: "Savoie",
        country: "France",
        altitude: { min: 1300, max: 2738 },
        snowBase: { lower: 90, upper: 180 },
        recentSnow: 28,
        price: 75,
        slopes: 150,
        lifts: 58,
        popular: true,
        website: "https://www.courchevel.com"
    },
    {
        id: "avoriaz",
        name: "Avoriaz",
        region: "Haute-Savoie",
        country: "France",
        altitude: { min: 1800, max: 2466 },
        snowBase: { lower: 140, upper: 200 },
        recentSnow: 35,
        price: 56,
        slopes: 75,
        lifts: 34,
        popular: true,
        website: "https://www.avoriaz.com"
    },
    {
        id: "morzine",
        name: "Morzine",
        region: "Haute-Savoie",
        country: "France",
        altitude: { min: 1000, max: 2100 },
        snowBase: { lower: 10, upper: 200 },
        recentSnow: 30,
        price: 54,
        slopes: 120,
        lifts: 49,
        popular: true,
        website: "https://www.morzine-avoriaz.com"
    },
    {
        id: "la-clusaz",
        name: "La Clusaz",
        region: "Haute-Savoie",
        country: "France",
        altitude: { min: 1100, max: 2600 },
        snowBase: { lower: 72, upper: 235 },
        recentSnow: 50,
        price: 49,
        slopes: 125,
        lifts: 49,
        popular: false,
        website: "https://www.laclusaz.com"
    },
    {
        id: "serre-chevalier",
        name: "Serre Chevalier",
        region: "Hautes-Alpes",
        country: "France",
        altitude: { min: 1200, max: 2800 },
        snowBase: { lower: 60, upper: 170 },
        recentSnow: 40,
        price: 52,
        slopes: 250,
        lifts: 61,
        popular: false,
        website: "https://www.serre-chevalier.com"
    },
    {
        id: "les-menuires",
        name: "Les Menuires",
        region: "Savoie",
        country: "France",
        altitude: { min: 1450, max: 2850 },
        snowBase: { lower: 100, upper: 185 },
        recentSnow: 32,
        price: 58,
        slopes: 160,
        lifts: 33,
        popular: false,
        website: "https://www.lesmenuires.com"
    },
    {
        id: "flaine",
        name: "Flaine",
        region: "Haute-Savoie",
        country: "France",
        altitude: { min: 1600, max: 2500 },
        snowBase: { lower: 110, upper: 195 },
        recentSnow: 28,
        price: 52,
        slopes: 140,
        lifts: 26,
        popular: false,
        website: "https://www.flaine.com"
    },

    // ========== SWITZERLAND ==========
    {
        id: "zermatt",
        name: "Zermatt",
        region: "Valais",
        country: "Switzerland",
        altitude: { min: 1620, max: 3883 },
        snowBase: { lower: 85, upper: 250 },
        recentSnow: 23,
        price: 92,
        slopes: 360,
        lifts: 52,
        popular: true,
        website: "https://www.zermatt.ch"
    },
    {
        id: "verbier",
        name: "Verbier",
        region: "Valais",
        country: "Switzerland",
        altitude: { min: 1500, max: 3330 },
        snowBase: { lower: 70, upper: 210 },
        recentSnow: 15,
        price: 85,
        slopes: 410,
        lifts: 67,
        popular: true,
        website: "https://www.verbier.ch"
    },
    {
        id: "st-moritz",
        name: "St. Moritz",
        region: "Graubünden",
        country: "Switzerland",
        altitude: { min: 1856, max: 3303 },
        snowBase: { lower: 60, upper: 190 },
        recentSnow: 30,
        price: 88,
        slopes: 350,
        lifts: 56,
        popular: true,
        website: "https://www.stmoritz.com"
    },
    {
        id: "davos-klosters",
        name: "Davos-Klosters",
        region: "Graubünden",
        country: "Switzerland",
        altitude: { min: 1560, max: 2844 },
        snowBase: { lower: 55, upper: 175 },
        recentSnow: 18,
        price: 79,
        slopes: 300,
        lifts: 57,
        popular: true,
        website: "https://www.davos.ch"
    },
    {
        id: "saas-fee",
        name: "Saas-Fee",
        region: "Valais",
        country: "Switzerland",
        altitude: { min: 1800, max: 3600 },
        snowBase: { lower: 90, upper: 230 },
        recentSnow: 20,
        price: 75,
        slopes: 100,
        lifts: 22,
        popular: false,
        website: "https://www.saas-fee.ch"
    },
    {
        id: "crans-montana",
        name: "Crans-Montana",
        region: "Valais",
        country: "Switzerland",
        altitude: { min: 1500, max: 3000 },
        snowBase: { lower: 50, upper: 180 },
        recentSnow: 22,
        price: 72,
        slopes: 140,
        lifts: 27,
        popular: false,
        website: "https://www.crans-montana.ch"
    },
    {
        id: "grindelwald",
        name: "Grindelwald",
        region: "Bern",
        country: "Switzerland",
        altitude: { min: 1034, max: 2971 },
        snowBase: { lower: 40, upper: 195 },
        recentSnow: 15,
        price: 78,
        slopes: 160,
        lifts: 28,
        popular: true,
        website: "https://www.grindelwald.swiss"
    },
    {
        id: "wengen",
        name: "Wengen",
        region: "Bern",
        country: "Switzerland",
        altitude: { min: 1274, max: 2970 },
        snowBase: { lower: 35, upper: 190 },
        recentSnow: 15,
        price: 76,
        slopes: 110,
        lifts: 19,
        popular: false,
        website: "https://www.wengen.swiss"
    },
    {
        id: "laax",
        name: "Laax",
        region: "Graubünden",
        country: "Switzerland",
        altitude: { min: 1100, max: 3018 },
        snowBase: { lower: 45, upper: 200 },
        recentSnow: 25,
        price: 82,
        slopes: 224,
        lifts: 28,
        popular: false,
        website: "https://www.laax.com"
    },
    {
        id: "villars-gryon",
        name: "Villars-Gryon",
        region: "Vaud",
        country: "Switzerland",
        altitude: { min: 1300, max: 2120 },
        snowBase: { lower: 60, upper: 140 },
        recentSnow: 23,
        price: 65,
        slopes: 100,
        lifts: 23,
        popular: false,
        website: "https://www.villars-diablerets.ch"
    },

    // ========== AUSTRIA ==========
    {
        id: "st-anton",
        name: "St. Anton am Arlberg",
        region: "Tyrol",
        country: "Austria",
        altitude: { min: 1304, max: 2811 },
        snowBase: { lower: 70, upper: 195 },
        recentSnow: 18,
        price: 72,
        slopes: 300,
        lifts: 88,
        popular: true,
        website: "https://www.stantonamarlberg.com"
    },
    {
        id: "ischgl",
        name: "Ischgl",
        region: "Tyrol",
        country: "Austria",
        altitude: { min: 1400, max: 2872 },
        snowBase: { lower: 65, upper: 180 },
        recentSnow: 15,
        price: 68,
        slopes: 239,
        lifts: 45,
        popular: true,
        website: "https://www.ischgl.com"
    },
    {
        id: "lech-zurs",
        name: "Lech-Zürs",
        region: "Vorarlberg",
        country: "Austria",
        altitude: { min: 1450, max: 2811 },
        snowBase: { lower: 85, upper: 200 },
        recentSnow: 20,
        price: 74,
        slopes: 305,
        lifts: 87,
        popular: true,
        website: "https://www.lech-zuers.at"
    },
    {
        id: "kitzbuehel",
        name: "Kitzbühel",
        region: "Tyrol",
        country: "Austria",
        altitude: { min: 800, max: 2000 },
        snowBase: { lower: 30, upper: 120 },
        recentSnow: 12,
        price: 66,
        slopes: 170,
        lifts: 57,
        popular: true,
        website: "https://www.kitzbuehel.com"
    },
    {
        id: "soelden",
        name: "Sölden",
        region: "Tyrol",
        country: "Austria",
        altitude: { min: 1350, max: 3340 },
        snowBase: { lower: 75, upper: 210 },
        recentSnow: 15,
        price: 70,
        slopes: 144,
        lifts: 31,
        popular: true,
        website: "https://www.soelden.com"
    },
    {
        id: "obergurgl",
        name: "Obergurgl-Hochgurgl",
        region: "Tyrol",
        country: "Austria",
        altitude: { min: 1930, max: 3080 },
        snowBase: { lower: 95, upper: 185 },
        recentSnow: 18,
        price: 65,
        slopes: 112,
        lifts: 25,
        popular: false,
        website: "https://www.obergurgl.com"
    },
    {
        id: "mayrhofen",
        name: "Mayrhofen",
        region: "Tyrol",
        country: "Austria",
        altitude: { min: 630, max: 2500 },
        snowBase: { lower: 25, upper: 160 },
        recentSnow: 10,
        price: 62,
        slopes: 142,
        lifts: 57,
        popular: false,
        website: "https://www.mayrhofen.at"
    },
    {
        id: "saalbach",
        name: "Saalbach-Hinterglemm",
        region: "Salzburg",
        country: "Austria",
        altitude: { min: 1003, max: 2096 },
        snowBase: { lower: 40, upper: 130 },
        recentSnow: 12,
        price: 67,
        slopes: 270,
        lifts: 70,
        popular: true,
        website: "https://www.saalbach.com"
    },
    {
        id: "zell-am-see",
        name: "Zell am See-Kaprun",
        region: "Salzburg",
        country: "Austria",
        altitude: { min: 757, max: 3029 },
        snowBase: { lower: 20, upper: 200 },
        recentSnow: 8,
        price: 64,
        slopes: 138,
        lifts: 52,
        popular: false,
        website: "https://www.zellamsee-kaprun.com"
    },
    {
        id: "innsbruck",
        name: "Innsbruck (Nordkette)",
        region: "Tyrol",
        country: "Austria",
        altitude: { min: 860, max: 2256 },
        snowBase: { lower: 30, upper: 150 },
        recentSnow: 10,
        price: 48,
        slopes: 15,
        lifts: 6,
        popular: false,
        website: "https://www.nordkette.com"
    },

    // ========== ITALY ==========
    {
        id: "cortina",
        name: "Cortina d'Ampezzo",
        region: "Veneto",
        country: "Italy",
        altitude: { min: 1224, max: 2930 },
        snowBase: { lower: 50, upper: 180 },
        recentSnow: 35,
        price: 72,
        slopes: 120,
        lifts: 37,
        popular: true,
        website: "https://www.dolomitisuperski.com/cortina"
    },
    {
        id: "courmayeur",
        name: "Courmayeur",
        region: "Aosta Valley",
        country: "Italy",
        altitude: { min: 1224, max: 2755 },
        snowBase: { lower: 70, upper: 195 },
        recentSnow: 26,
        price: 58,
        slopes: 100,
        lifts: 18,
        popular: true,
        website: "https://www.courmayeur-montblanc.com"
    },
    {
        id: "val-gardena",
        name: "Val Gardena (Selva)",
        region: "Trentino-Alto Adige",
        country: "Italy",
        altitude: { min: 1236, max: 2518 },
        snowBase: { lower: 45, upper: 170 },
        recentSnow: 30,
        price: 65,
        slopes: 175,
        lifts: 79,
        popular: true,
        website: "https://www.valgardena.it"
    },
    {
        id: "alta-badia",
        name: "Alta Badia",
        region: "Trentino-Alto Adige",
        country: "Italy",
        altitude: { min: 1324, max: 2778 },
        snowBase: { lower: 40, upper: 165 },
        recentSnow: 30,
        price: 64,
        slopes: 130,
        lifts: 53,
        popular: true,
        website: "https://www.altabadia.org"
    },
    {
        id: "madonna-di-campiglio",
        name: "Madonna di Campiglio",
        region: "Trentino-Alto Adige",
        country: "Italy",
        altitude: { min: 1550, max: 2504 },
        snowBase: { lower: 60, upper: 150 },
        recentSnow: 30,
        price: 60,
        slopes: 150,
        lifts: 57,
        popular: true,
        website: "https://www.campigliodolomiti.it"
    },
    {
        id: "livigno",
        name: "Livigno",
        region: "Lombardy",
        country: "Italy",
        altitude: { min: 1816, max: 2798 },
        snowBase: { lower: 80, upper: 175 },
        recentSnow: 20,
        price: 52,
        slopes: 115,
        lifts: 31,
        popular: true,
        website: "https://www.livigno.eu"
    },
    {
        id: "cervinia",
        name: "Cervinia",
        region: "Aosta Valley",
        country: "Italy",
        altitude: { min: 2050, max: 3480 },
        snowBase: { lower: 100, upper: 240 },
        recentSnow: 22,
        price: 58,
        slopes: 150,
        lifts: 21,
        popular: true,
        website: "https://www.cervinia.it"
    },
    {
        id: "sestriere",
        name: "Sestriere",
        region: "Piedmont",
        country: "Italy",
        altitude: { min: 1350, max: 2823 },
        snowBase: { lower: 55, upper: 160 },
        recentSnow: 25,
        price: 48,
        slopes: 400,
        lifts: 70,
        popular: false,
        website: "https://www.vialattea.it"
    },
    {
        id: "bardonecchia",
        name: "Bardonecchia",
        region: "Piedmont",
        country: "Italy",
        altitude: { min: 1312, max: 2800 },
        snowBase: { lower: 50, upper: 170 },
        recentSnow: 40,
        price: 42,
        slopes: 100,
        lifts: 23,
        popular: false,
        website: "https://www.bardonecchiaski.com"
    },
    {
        id: "arabba",
        name: "Arabba (Marmolada)",
        region: "Veneto",
        country: "Italy",
        altitude: { min: 1602, max: 3269 },
        snowBase: { lower: 55, upper: 190 },
        recentSnow: 35,
        price: 64,
        slopes: 62,
        lifts: 26,
        popular: false,
        website: "https://www.arabba.it"
    }
];

// Helper function to find resort by ID
function getResortById(id) {
    return skiResorts.find(r => r.id === id);
}
